name: build wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel auditwheel
    - name: Build
      run: |
        pip wheel .
    - name: Get wheel filename
      run: |
        # ensure there's exactly one wheel
        ls *.whl | wc -l | grep -Fqx 1
        printf "WHEEL_FILENAME=%s\n" *.whl | tee -a "$GITHUB_ENV"
    - name: auditwheel
      run: |
        auditwheel repair ${{ env.WHEEL_FILENAME }} -w wheelhouse
    - name: Store wheel artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: ${{ env.WHEEL_FILENAME }}
